src/Entity/Contact.php
<?php

namespace App\Entity;

use App\Repository\ContactRepository;
use Doctrine\DBAL\Types\Types;
use Doctrine\ORM\Mapping as ORM;
use Symfony\Component\Serializer\Annotation\Groups;
use Symfony\Component\Validator\Constraints as Assert;
use ApiPlatform\Metadata\ApiResource; 
use Symfony\Component\Validator\Constraints;

#[ORM\Entity(repositoryClass: ContactRepository::class)]
// #[ApiResource(
//     normalizationContext: ['groups' => ['read']],
//     denormalizationContext: ['groups' => ['write']],
// )]
class Contact
{
    #[ORM\Id]
    #[ORM\GeneratedValue]
    #[ORM\Column]
    #[Groups('read')]
    private ?int $id = null;

    #[ORM\Column(length: 50)]
    #[Groups('read')]
    #[Constraints\NotBlank()]
    #[Constraints\Regex('/^[A-Za-zÀ-ÖØ-öø-ÿ\'-]+(?:\s[A-Za-zÀ-ÖØ-öø-ÿ\'-]+)*$/', message: 'Nom invalide, le champ ne peut contenir de Caractère Spéciaux')]
    private ?string $Nom = null;

    #[ORM\Column(length: 50)]
    #[Groups('read')]
    #[Constraints\NotBlank()]
    #[Constraints\Regex('/^[A-Za-zÀ-ÖØ-öø-ÿ\'-]+(?:\s[A-Za-zÀ-ÖØ-öø-ÿ\'-]+)*$/', message: 'Prenom invalide, le champ ne peut contenir de Caractère Spéciaux')]
    private ?string $Prenom = null;

    #[Assert\NotBlank]
    #[ORM\Column(length: 255)]
    #[Groups('read')]
    #[Constraints\NotBlank()]
    #[Assert\Email(
        message: 'l\'adresse email : {{ value }} n\'est pas valide.',
    )]
    private ?string $Email = null;

    #[ORM\Column(length: 20)]
    #[Groups('read')]
    #[Constraints\Regex('/(0|\\+33|0033)[1-9][0-9]{8}/', message: 'numero de telephone invalide')]
    #[Constraints\NotBlank()]
    private ?string $Telephone = null;

    #[Assert\NotBlank]
    #[ORM\Column(type: Types::TEXT)]
    #[Groups('read')]
    #[Constraints\NotBlank()]
    #[Constraints\Length(min: 20,minMessage:'Votre demande doit contenir un minimum {{ limit }} caractere')]
    private ?string $Demande = null;

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getNom(): ?string
    {
        return $this->Nom;
    }

    public function setNom(string $Nom): static
    {
        $this->Nom = $Nom;

        return $this;
    }

    public function getPrenom(): ?string
    {
        return $this->Prenom;
    }

    public function setPrenom(string $Prenom): static
    {
        $this->Prenom = $Prenom;

        return $this;
    }

    public function getEmail(): ?string
    {
        return $this->Email;
    }

    public function setEmail(string $Email): static
    {
        $this->Email = $Email;

        return $this;
    }

    public function getTelephone(): ?string
    {
        return $this->Telephone;
    }

    public function setTelephone(string $Telephone): static
    {
        $this->Telephone = $Telephone;

        return $this;
    }

    public function getDemande(): ?string
    {
        return $this->Demande;
    }

    public function setDemande(string $Demande): static
    {
        $this->Demande = $Demande;

        return $this;
    }
}

templates/connexion/NewAdresse.html.twig
{% extends 'base.html.twig' %}

{% block title %}nouvelle adresse
{% endblock %}

{% block body %}

	{{ form_start(form) }}
	<div class='container mt-4'>
		<div class='row justify-content-center position-relative'>

			<div class="col-md-6 col-12 mb-3">
				{{ form_row(form.nom) }}
			</div>

			<div class="col-md-6 col-12 mb-3">
				{{ form_row(form.prenom) }}
			</div>

			<div class="col-12 mb-3">
				{{ form_row(form.telephone) }}
			</div>

			<div class="col-12 mb-3">
				{{ form_row(form.adresse) }}
			</div>

			<div class="col-md-6 col-12 mb-3">
				{{ form_row(form.cp) }}
			</div>

			<div class="col-md-6 col-12 mb-3">
				{{ form_row(form.ville) }}
			</div>

			<div class="col-md-6 col-12 mb-3">
				{{ form_row(form.agreeTerms) }}
			</div>

			<div class="col-md-6 col-12 position-relative mt-5">
				{{ form_row(form.save, {
                        'label': 'Enregistrer',
                        'label_attr': {'class': 'btn position-absolute bottom-0 end-0'}}
				)}}
			</div>
			
		</div>
	</div>

	{{ form_end(form) }}


{% endblock %}

templates/connexion/NewMoyendepaiment.html.twig
{% extends 'base.html.twig' %}

{% block title %}Moyen de paiement
{% endblock %}

{% block body %}

	{{ form_start(form) }}
	<div class='container mt-4'>
		<div class='row justify-content-center position-relative'>

			<div class="col-md-6 col-12 mb-3">
				{{ form_row(form.numeros_de_carte) }}
			</div>

			<div class="col-md-6 col-12 mb-3">
				{{ form_row(form.expiration) }}
			</div>

			<div class="col-12 mb-3">
				{{ form_row(form.code_securite) }}
			</div>

			<div class="col-12 mb-3">
				{{ form_row(form.nom_titulaire) }}
			</div>

			<div class="col position-relative mt-5">
				<button type="submit" class="btn position-absolute bottom-0 end-0">Enregistrer</button>
			</div>

		</div>
	</div>

	{{ form_end(form) }}


{% endblock %}

templates/connexion/detail.html.twig
{% extends 'base.html.twig' %}

{% block title %}{% endblock %}

{% block body %}
	<div class="container">
		<h1 class="my-2">Detail du compte</h1>
		<div class="row justify-content-around">
			<h2 class="col-12">mes informations personnel :</h2>

			{# <a class="link-body-emphasis link-offset-2 link-underline-opacity-0 link-underline-opacity-75-hover justify-content-center col-4" href="{{ path ('app_newadresse', {nom: app.user.nom,prenom: app.user.prenom}) }}">
			        <button class="btn btn-primary">Ajouter un adresse de livraison</button></a> #}

			<div class="card col-11 col-md-4 text-bg-primary my-3">
				<div class="card-header">Adresse facturation</div>
				<div class="card-body">
					<h5 class="card-title">Nom :
						{{ user.Nom | upper }}
						{{ user.prenom }}</h5>
					<p class="card-text">Email :
						{{ user.email }}</p>
					<p class="card-text">Télèphone :
						{{ user.telephone }}</p>
					<p class="card-text">Adresse :
						{{ user.adresse }}</p>
					<p class="card-text">Ville :
						{{ user.ville }}</p>
					<p class="card-text">Code postal :
						{{ user.cp }}</p>
					<a class="link-body-emphasis link-offset-2 link-underline-opacity-0 link-underline-opacity-75-hover justify-content-center position-absolute top-0 end-0" href="{{ path ('app_editprofil', {nom: app.user.nom,prenom: app.user.prenom}) }}">
						<button class="btn btn-primary">Modifier</button>
					</a>
				</div>
			</div>

			{% for adresse in user.adresseLivraisons %}

				<div class="card col-11 col-md-4 text-bg-primary my-3">
					<div class="card-header">Adresse livraison</div>
					<div class="card-body">
						<h5 class="card-title">Nom :
							{{ adresse.nom | upper }}
							{{ adresse.prenom }}</h5>
						<p class="card-text">Télèphone :
							{{ adresse.telephone }}</p>
						<p class="card-text">Adresse :
							{{ adresse.adresse }}</p>
						<p class="card-text">Ville :
							{{ adresse.ville }}</p>
						<p class="card-text">Code postal :
							{{ adresse.cp }}</p>
						<div class="position-absolute top-0 end-0">
							<a class="link-body-emphasis link-offset-2 link-underline-opacity-0 link-underline-opacity-75-hover justify-content-center" href=" {{ path ('app_editadresse', {nom: app.user.nom,prenom: app.user.prenom,id: adresse.id}) }}">
								<button class="btn btn-primary">Modifier</button>
							</a>
							<a class="link-body-emphasis link-offset-2 link-underline-opacity-0 link-underline-opacity-75-hover justify-content-center" href=" {{ path ('app_suppadresse', {nom: app.user.nom,prenom: app.user.prenom,id: adresse.id}) }}">
								<button class="btn btn-danger">Supprimer</button>
							</a>
						</div>
					</div>
				</div>
			{% else %}
				<a class="link-body-emphasis link-offset-2 link-underline-opacity-0 link-underline-opacity-75-hover justify-content-center col-4" href="{{ path ('app_newadresse', {nom: app.user.nom,prenom: app.user.prenom}) }}">
					<button class="btn btn-primary">Ajouter un adresse de livraison</button>
				</a>
			{% endfor %}

		</div>

		<div class="row justify-content-around">
			<h2 class="col-12">mon Moyen de paiement</h2>
			{# <a class="link-body-emphasis link-offset-2 link-underline-opacity-0 link-underline-opacity-75-hover justify-content-center col-4" href="{{ path ('app_newmoyenpaiement', {nom: app.user.nom,prenom: app.user.prenom}) }}">
			        <button class="btn btn-primary">Ajouter une carte bancaire</button></a> #}

			{% for paiement in user.moyenPaiements %}

				<div class="card col-11 col-md-4 text-bg-primary my-3">
					<div class="card-header">Moyen de paiement
					</div>
					<div class="card-body">
						<h5 class="card-title">Titulaire :
							{{ paiement.NomTitulaire | upper }}</h5>
						<p class="card-text">Numeros :
							{{ paiement.numerosdecarte }}</p>
						<p class="card-text">expiration :
							{{ paiement.expiration }}</p>
						{# <p class="card-text"> {{ paiement.codesecurite }}</p> #}
						<div class="position-absolute top-0 end-0">
							<a class="link-body-emphasis link-offset-2 link-underline-opacity-0 link-underline-opacity-75-hover justify-content-center" href=" {{ path ('app_editmoyenpaiement', {nom: app.user.nom,prenom: app.user.prenom,id: paiement.id}) }}">
								<button class="btn btn-primary">Modifier</button>
							</a>
							<a class="link-body-emphasis link-offset-2 link-underline-opacity-0 link-underline-opacity-75-hover justify-content-center" href=" {{ path ('app_suppmoyenpaiement', {nom: app.user.nom,prenom: app.user.prenom,id: paiement.id}) }}">
								<button class="btn btn-danger">Supprimer</button>
							</a>
						</div>
					</div>
				</div>
			{% else %}
				<a class="link-body-emphasis link-offset-2 link-underline-opacity-0 link-underline-opacity-75-hover justify-content-center col-4" href="{{ path ('app_newmoyenpaiement', {nom: app.user.nom,prenom: app.user.prenom}) }}">
					<button class="btn btn-primary">Ajouter une carte bancaire</button>
				</a>

			{% endfor %}

		</div>

		<div class="row">
			<h2 class="col-12">Mes commandes</h2>

			<table class="col-md-12 col-11 table table-striped-columns">
				<thead>
					<tr>
						<th class='text-center'>date de la commande</th>
						<th class='text-center'>etat</th>
						<th class='text-center d-none d-md-block'>detail commande</th>
						<th class='text-center'>total</th>
					</tr>
				</thead>
				<tbody>
					{% for commande in commandes  %}
						<tr>
							<th class='text-center align-middle'>{{ commande.DateCommande | date("d/m/Y") }}</th>

							<th class='text-center align-middle'>
								{% if (commande.etat == 0) %}enregistrée/payée
								{% elseif (commande.etat == 1) %}
									en préparation
								{% elseif (commande.etat == 2) %}
									en cours de livraison
								{% elseif (commande.etat == 3) %}
									livrée
								{% endif %}
							</th>

							<th class='text-start d-none d-md-block'>
								<table class="table">
									<thead>
										<tr>
											<th>Nom</th>
											<th>Prix</th>
											<th>quantite</th>
										</tr>
									</thead>
									<tbody>
										{% for detail in commande.details  %}

											<tr>
												<td>{{ detail.plats.libelle }}</td>
												<td>{{ detail.plats.prix }}</td>
												<td>{{ detail.quantite}}</td>
											</tr>

										{% endfor %}
									</tbody>
								</table>
							</th>

							<th class='text-center align-middle'>{{ commande.total }}</th>

						</tr>
					{% endfor %}
				</tbody>
			</table>

		</div>
	</div>
{% endblock %}

templates/connexion/edit.html.twig
{% extends 'base.html.twig' %}

{% block title %}Modifier adresse
{% endblock %}

{% block body %}

	{{ form_start(form) }}
	<div class='container mt-4'>
		<div class='row justify-content-center'>


			<div class="col-md-6 col-12 mb-3">
				{{ form_row(form.nom) }}
			</div>

			<div class="col-md-6 col-12 mb-3">
				{{ form_row(form.prenom) }}
			</div>

			<div class="col-md-6 col-12 mb-3">
				{{ form_row(form.email) }}
			</div>

			<div class="col-md-6 col-12 mb-3">
				{{ form_row(form.telephone) }}
			</div>

			<div class="col-12 mb-3">
				{{ form_row(form.plainPassword) }}
			</div>

			<div class="col-12 mb-3">
				{{ form_row(form.adresse) }}
			</div>

			<div class="col-md-6 col-12 mb-3">
				{{ form_row(form.cp) }}
			</div>

			<div class="col-md-6 col-12 mb-3">
				{{ form_row(form.ville) }}
			</div>

			<div class="col-md-6 col-12 mb-3">
				{{ form_row(form.agreeTerms) }}
			</div>

			{# <div class="col mb-3">
			                    {{ form_row(form.agreeTerms) }}
			                </div> #}

			<div class="col-md-6 col-12 position-relative">
				<button type="submit" class="btn position-absolute bottom-0 end-0">Enregistrer</button>
			</div>

		</div>
	</div>

	{{ form_end(form) }}


{% endblock %}